# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vjepa_pb2 as vjepa__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vjepa_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VJEPAServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CompareFrames = channel.unary_unary(
                '/vjepa.VJEPAService/CompareFrames',
                request_serializer=vjepa__pb2.CompareFramesRequest.SerializeToString,
                response_deserializer=vjepa__pb2.CompareFramesResponse.FromString,
                _registered_method=True)
        self.DetectStability = channel.unary_unary(
                '/vjepa.VJEPAService/DetectStability',
                request_serializer=vjepa__pb2.DetectStabilityRequest.SerializeToString,
                response_deserializer=vjepa__pb2.DetectStabilityResponse.FromString,
                _registered_method=True)
        self.GenerateEmbedding = channel.unary_unary(
                '/vjepa.VJEPAService/GenerateEmbedding',
                request_serializer=vjepa__pb2.GenerateEmbeddingRequest.SerializeToString,
                response_deserializer=vjepa__pb2.GenerateEmbeddingResponse.FromString,
                _registered_method=True)
        self.BatchCompare = channel.unary_unary(
                '/vjepa.VJEPAService/BatchCompare',
                request_serializer=vjepa__pb2.BatchCompareRequest.SerializeToString,
                response_deserializer=vjepa__pb2.BatchCompareResponse.FromString,
                _registered_method=True)
        self.AnalyzeChange = channel.unary_unary(
                '/vjepa.VJEPAService/AnalyzeChange',
                request_serializer=vjepa__pb2.AnalyzeChangeRequest.SerializeToString,
                response_deserializer=vjepa__pb2.AnalyzeChangeResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/vjepa.VJEPAService/HealthCheck',
                request_serializer=vjepa__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=vjepa__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class VJEPAServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CompareFrames(self, request, context):
        """Compare two frames and return semantic similarity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectStability(self, request, context):
        """Detect if UI is stable (not loading/animating)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateEmbedding(self, request, context):
        """Generate embedding vector for a frame
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchCompare(self, request, context):
        """Compare multiple frame pairs (batch)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeChange(self, request, context):
        """Analyze and describe changes between frames
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VJEPAServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CompareFrames': grpc.unary_unary_rpc_method_handler(
                    servicer.CompareFrames,
                    request_deserializer=vjepa__pb2.CompareFramesRequest.FromString,
                    response_serializer=vjepa__pb2.CompareFramesResponse.SerializeToString,
            ),
            'DetectStability': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectStability,
                    request_deserializer=vjepa__pb2.DetectStabilityRequest.FromString,
                    response_serializer=vjepa__pb2.DetectStabilityResponse.SerializeToString,
            ),
            'GenerateEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateEmbedding,
                    request_deserializer=vjepa__pb2.GenerateEmbeddingRequest.FromString,
                    response_serializer=vjepa__pb2.GenerateEmbeddingResponse.SerializeToString,
            ),
            'BatchCompare': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchCompare,
                    request_deserializer=vjepa__pb2.BatchCompareRequest.FromString,
                    response_serializer=vjepa__pb2.BatchCompareResponse.SerializeToString,
            ),
            'AnalyzeChange': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeChange,
                    request_deserializer=vjepa__pb2.AnalyzeChangeRequest.FromString,
                    response_serializer=vjepa__pb2.AnalyzeChangeResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=vjepa__pb2.HealthCheckRequest.FromString,
                    response_serializer=vjepa__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vjepa.VJEPAService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vjepa.VJEPAService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VJEPAService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CompareFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vjepa.VJEPAService/CompareFrames',
            vjepa__pb2.CompareFramesRequest.SerializeToString,
            vjepa__pb2.CompareFramesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectStability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vjepa.VJEPAService/DetectStability',
            vjepa__pb2.DetectStabilityRequest.SerializeToString,
            vjepa__pb2.DetectStabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vjepa.VJEPAService/GenerateEmbedding',
            vjepa__pb2.GenerateEmbeddingRequest.SerializeToString,
            vjepa__pb2.GenerateEmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchCompare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vjepa.VJEPAService/BatchCompare',
            vjepa__pb2.BatchCompareRequest.SerializeToString,
            vjepa__pb2.BatchCompareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vjepa.VJEPAService/AnalyzeChange',
            vjepa__pb2.AnalyzeChangeRequest.SerializeToString,
            vjepa__pb2.AnalyzeChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vjepa.VJEPAService/HealthCheck',
            vjepa__pb2.HealthCheckRequest.SerializeToString,
            vjepa__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
