// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: internal/vjepa/proto/vjepa.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VJEPAService_CompareFrames_FullMethodName     = "/vjepa.VJEPAService/CompareFrames"
	VJEPAService_DetectStability_FullMethodName   = "/vjepa.VJEPAService/DetectStability"
	VJEPAService_GenerateEmbedding_FullMethodName = "/vjepa.VJEPAService/GenerateEmbedding"
	VJEPAService_BatchCompare_FullMethodName      = "/vjepa.VJEPAService/BatchCompare"
	VJEPAService_AnalyzeChange_FullMethodName     = "/vjepa.VJEPAService/AnalyzeChange"
	VJEPAService_HealthCheck_FullMethodName       = "/vjepa.VJEPAService/HealthCheck"
)

// VJEPAServiceClient is the client API for VJEPAService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VJEPAServiceClient interface {
	// Compare two frames and return semantic similarity
	CompareFrames(ctx context.Context, in *CompareFramesRequest, opts ...grpc.CallOption) (*CompareFramesResponse, error)
	// Detect if UI is stable (not loading/animating)
	DetectStability(ctx context.Context, in *DetectStabilityRequest, opts ...grpc.CallOption) (*DetectStabilityResponse, error)
	// Generate embedding vector for a frame
	GenerateEmbedding(ctx context.Context, in *GenerateEmbeddingRequest, opts ...grpc.CallOption) (*GenerateEmbeddingResponse, error)
	// Compare multiple frame pairs (batch)
	BatchCompare(ctx context.Context, in *BatchCompareRequest, opts ...grpc.CallOption) (*BatchCompareResponse, error)
	// Analyze and describe changes between frames
	AnalyzeChange(ctx context.Context, in *AnalyzeChangeRequest, opts ...grpc.CallOption) (*AnalyzeChangeResponse, error)
	// Health check
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type vJEPAServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVJEPAServiceClient(cc grpc.ClientConnInterface) VJEPAServiceClient {
	return &vJEPAServiceClient{cc}
}

func (c *vJEPAServiceClient) CompareFrames(ctx context.Context, in *CompareFramesRequest, opts ...grpc.CallOption) (*CompareFramesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompareFramesResponse)
	err := c.cc.Invoke(ctx, VJEPAService_CompareFrames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vJEPAServiceClient) DetectStability(ctx context.Context, in *DetectStabilityRequest, opts ...grpc.CallOption) (*DetectStabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectStabilityResponse)
	err := c.cc.Invoke(ctx, VJEPAService_DetectStability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vJEPAServiceClient) GenerateEmbedding(ctx context.Context, in *GenerateEmbeddingRequest, opts ...grpc.CallOption) (*GenerateEmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateEmbeddingResponse)
	err := c.cc.Invoke(ctx, VJEPAService_GenerateEmbedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vJEPAServiceClient) BatchCompare(ctx context.Context, in *BatchCompareRequest, opts ...grpc.CallOption) (*BatchCompareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCompareResponse)
	err := c.cc.Invoke(ctx, VJEPAService_BatchCompare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vJEPAServiceClient) AnalyzeChange(ctx context.Context, in *AnalyzeChangeRequest, opts ...grpc.CallOption) (*AnalyzeChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeChangeResponse)
	err := c.cc.Invoke(ctx, VJEPAService_AnalyzeChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vJEPAServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, VJEPAService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VJEPAServiceServer is the server API for VJEPAService service.
// All implementations must embed UnimplementedVJEPAServiceServer
// for forward compatibility.
type VJEPAServiceServer interface {
	// Compare two frames and return semantic similarity
	CompareFrames(context.Context, *CompareFramesRequest) (*CompareFramesResponse, error)
	// Detect if UI is stable (not loading/animating)
	DetectStability(context.Context, *DetectStabilityRequest) (*DetectStabilityResponse, error)
	// Generate embedding vector for a frame
	GenerateEmbedding(context.Context, *GenerateEmbeddingRequest) (*GenerateEmbeddingResponse, error)
	// Compare multiple frame pairs (batch)
	BatchCompare(context.Context, *BatchCompareRequest) (*BatchCompareResponse, error)
	// Analyze and describe changes between frames
	AnalyzeChange(context.Context, *AnalyzeChangeRequest) (*AnalyzeChangeResponse, error)
	// Health check
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedVJEPAServiceServer()
}

// UnimplementedVJEPAServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVJEPAServiceServer struct{}

func (UnimplementedVJEPAServiceServer) CompareFrames(context.Context, *CompareFramesRequest) (*CompareFramesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompareFrames not implemented")
}
func (UnimplementedVJEPAServiceServer) DetectStability(context.Context, *DetectStabilityRequest) (*DetectStabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectStability not implemented")
}
func (UnimplementedVJEPAServiceServer) GenerateEmbedding(context.Context, *GenerateEmbeddingRequest) (*GenerateEmbeddingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateEmbedding not implemented")
}
func (UnimplementedVJEPAServiceServer) BatchCompare(context.Context, *BatchCompareRequest) (*BatchCompareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCompare not implemented")
}
func (UnimplementedVJEPAServiceServer) AnalyzeChange(context.Context, *AnalyzeChangeRequest) (*AnalyzeChangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeChange not implemented")
}
func (UnimplementedVJEPAServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedVJEPAServiceServer) mustEmbedUnimplementedVJEPAServiceServer() {}
func (UnimplementedVJEPAServiceServer) testEmbeddedByValue()                      {}

// UnsafeVJEPAServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VJEPAServiceServer will
// result in compilation errors.
type UnsafeVJEPAServiceServer interface {
	mustEmbedUnimplementedVJEPAServiceServer()
}

func RegisterVJEPAServiceServer(s grpc.ServiceRegistrar, srv VJEPAServiceServer) {
	// If the following call panics, it indicates UnimplementedVJEPAServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VJEPAService_ServiceDesc, srv)
}

func _VJEPAService_CompareFrames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareFramesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VJEPAServiceServer).CompareFrames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VJEPAService_CompareFrames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VJEPAServiceServer).CompareFrames(ctx, req.(*CompareFramesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VJEPAService_DetectStability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectStabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VJEPAServiceServer).DetectStability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VJEPAService_DetectStability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VJEPAServiceServer).DetectStability(ctx, req.(*DetectStabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VJEPAService_GenerateEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateEmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VJEPAServiceServer).GenerateEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VJEPAService_GenerateEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VJEPAServiceServer).GenerateEmbedding(ctx, req.(*GenerateEmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VJEPAService_BatchCompare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCompareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VJEPAServiceServer).BatchCompare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VJEPAService_BatchCompare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VJEPAServiceServer).BatchCompare(ctx, req.(*BatchCompareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VJEPAService_AnalyzeChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VJEPAServiceServer).AnalyzeChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VJEPAService_AnalyzeChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VJEPAServiceServer).AnalyzeChange(ctx, req.(*AnalyzeChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VJEPAService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VJEPAServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VJEPAService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VJEPAServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VJEPAService_ServiceDesc is the grpc.ServiceDesc for VJEPAService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VJEPAService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vjepa.VJEPAService",
	HandlerType: (*VJEPAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CompareFrames",
			Handler:    _VJEPAService_CompareFrames_Handler,
		},
		{
			MethodName: "DetectStability",
			Handler:    _VJEPAService_DetectStability_Handler,
		},
		{
			MethodName: "GenerateEmbedding",
			Handler:    _VJEPAService_GenerateEmbedding_Handler,
		},
		{
			MethodName: "BatchCompare",
			Handler:    _VJEPAService_BatchCompare_Handler,
		},
		{
			MethodName: "AnalyzeChange",
			Handler:    _VJEPAService_AnalyzeChange_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _VJEPAService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/vjepa/proto/vjepa.proto",
}
