// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: internal/vjepa/proto/vjepa.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompareFramesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Image data (base64 or URI)
	BaselineData []byte `protobuf:"bytes,1,opt,name=baseline_data,json=baselineData,proto3" json:"baseline_data,omitempty"`
	BaselineUri  string `protobuf:"bytes,2,opt,name=baseline_uri,json=baselineUri,proto3" json:"baseline_uri,omitempty"`
	ActualData   []byte `protobuf:"bytes,3,opt,name=actual_data,json=actualData,proto3" json:"actual_data,omitempty"`
	ActualUri    string `protobuf:"bytes,4,opt,name=actual_uri,json=actualUri,proto3" json:"actual_uri,omitempty"`
	// Context for better comparison
	Context string `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"` // e.g., "login form submission"
	// Comparison settings
	Settings      *CompareSettings `protobuf:"bytes,6,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareFramesRequest) Reset() {
	*x = CompareFramesRequest{}
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareFramesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareFramesRequest) ProtoMessage() {}

func (x *CompareFramesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareFramesRequest.ProtoReflect.Descriptor instead.
func (*CompareFramesRequest) Descriptor() ([]byte, []int) {
	return file_internal_vjepa_proto_vjepa_proto_rawDescGZIP(), []int{0}
}

func (x *CompareFramesRequest) GetBaselineData() []byte {
	if x != nil {
		return x.BaselineData
	}
	return nil
}

func (x *CompareFramesRequest) GetBaselineUri() string {
	if x != nil {
		return x.BaselineUri
	}
	return ""
}

func (x *CompareFramesRequest) GetActualData() []byte {
	if x != nil {
		return x.ActualData
	}
	return nil
}

func (x *CompareFramesRequest) GetActualUri() string {
	if x != nil {
		return x.ActualUri
	}
	return ""
}

func (x *CompareFramesRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *CompareFramesRequest) GetSettings() *CompareSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type CompareSettings struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SimilarityThreshold float32                `protobuf:"fixed32,1,opt,name=similarity_threshold,json=similarityThreshold,proto3" json:"similarity_threshold,omitempty"` // Default 0.85
	IgnoreColors        bool                   `protobuf:"varint,2,opt,name=ignore_colors,json=ignoreColors,proto3" json:"ignore_colors,omitempty"`                       // Focus on structure, not colors
	IgnoreTextContent   bool                   `protobuf:"varint,3,opt,name=ignore_text_content,json=ignoreTextContent,proto3" json:"ignore_text_content,omitempty"`      // Focus on layout, not text
	IgnoreRegions       []*Region              `protobuf:"bytes,4,rep,name=ignore_regions,json=ignoreRegions,proto3" json:"ignore_regions,omitempty"`                     // Areas to ignore (e.g., timestamps)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CompareSettings) Reset() {
	*x = CompareSettings{}
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareSettings) ProtoMessage() {}

func (x *CompareSettings) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareSettings.ProtoReflect.Descriptor instead.
func (*CompareSettings) Descriptor() ([]byte, []int) {
	return file_internal_vjepa_proto_vjepa_proto_rawDescGZIP(), []int{1}
}

func (x *CompareSettings) GetSimilarityThreshold() float32 {
	if x != nil {
		return x.SimilarityThreshold
	}
	return 0
}

func (x *CompareSettings) GetIgnoreColors() bool {
	if x != nil {
		return x.IgnoreColors
	}
	return false
}

func (x *CompareSettings) GetIgnoreTextContent() bool {
	if x != nil {
		return x.IgnoreTextContent
	}
	return false
}

func (x *CompareSettings) GetIgnoreRegions() []*Region {
	if x != nil {
		return x.IgnoreRegions
	}
	return nil
}

type Region struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Region) Reset() {
	*x = Region{}
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Region) ProtoMessage() {}

func (x *Region) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Region.ProtoReflect.Descriptor instead.
func (*Region) Descriptor() ([]byte, []int) {
	return file_internal_vjepa_proto_vjepa_proto_rawDescGZIP(), []int{2}
}

func (x *Region) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Region) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Region) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Region) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type CompareFramesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SimilarityScore float32                `protobuf:"fixed32,1,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"` // 0.0 to 1.0
	SemanticMatch   bool                   `protobuf:"varint,2,opt,name=semantic_match,json=semanticMatch,proto3" json:"semantic_match,omitempty"`        // True if semantically equivalent
	Confidence      float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`                                  // Model confidence
	// Detailed analysis
	ChangedRegions []*ChangedRegion `protobuf:"bytes,4,rep,name=changed_regions,json=changedRegions,proto3" json:"changed_regions,omitempty"`
	Analysis       string           `protobuf:"bytes,5,opt,name=analysis,proto3" json:"analysis,omitempty"` // Human-readable description
	// Embeddings (for caching)
	BaselineEmbedding []byte `protobuf:"bytes,6,opt,name=baseline_embedding,json=baselineEmbedding,proto3" json:"baseline_embedding,omitempty"`
	ActualEmbedding   []byte `protobuf:"bytes,7,opt,name=actual_embedding,json=actualEmbedding,proto3" json:"actual_embedding,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CompareFramesResponse) Reset() {
	*x = CompareFramesResponse{}
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareFramesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareFramesResponse) ProtoMessage() {}

func (x *CompareFramesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareFramesResponse.ProtoReflect.Descriptor instead.
func (*CompareFramesResponse) Descriptor() ([]byte, []int) {
	return file_internal_vjepa_proto_vjepa_proto_rawDescGZIP(), []int{3}
}

func (x *CompareFramesResponse) GetSimilarityScore() float32 {
	if x != nil {
		return x.SimilarityScore
	}
	return 0
}

func (x *CompareFramesResponse) GetSemanticMatch() bool {
	if x != nil {
		return x.SemanticMatch
	}
	return false
}

func (x *CompareFramesResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *CompareFramesResponse) GetChangedRegions() []*ChangedRegion {
	if x != nil {
		return x.ChangedRegions
	}
	return nil
}

func (x *CompareFramesResponse) GetAnalysis() string {
	if x != nil {
		return x.Analysis
	}
	return ""
}

func (x *CompareFramesResponse) GetBaselineEmbedding() []byte {
	if x != nil {
		return x.BaselineEmbedding
	}
	return nil
}

func (x *CompareFramesResponse) GetActualEmbedding() []byte {
	if x != nil {
		return x.ActualEmbedding
	}
	return nil
}

type ChangedRegion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        *Region                `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	ChangeType    string                 `protobuf:"bytes,2,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"` // added, removed, modified
	Significance  float32                `protobuf:"fixed32,3,opt,name=significance,proto3" json:"significance,omitempty"`             // How significant is this change (0-1)
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                 // What changed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangedRegion) Reset() {
	*x = ChangedRegion{}
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangedRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangedRegion) ProtoMessage() {}

func (x *ChangedRegion) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangedRegion.ProtoReflect.Descriptor instead.
func (*ChangedRegion) Descriptor() ([]byte, []int) {
	return file_internal_vjepa_proto_vjepa_proto_rawDescGZIP(), []int{4}
}

func (x *ChangedRegion) GetRegion() *Region {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *ChangedRegion) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

func (x *ChangedRegion) GetSignificance() float32 {
	if x != nil {
		return x.Significance
	}
	return 0
}

func (x *ChangedRegion) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DetectStabilityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sequence of frames to analyze
	Frames    [][]byte `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"`
	FrameUris []string `protobuf:"bytes,2,rep,name=frame_uris,json=frameUris,proto3" json:"frame_uris,omitempty"`
	// Settings
	StabilityThreshold float32 `protobuf:"fixed32,3,opt,name=stability_threshold,json=stabilityThreshold,proto3" json:"stability_threshold,omitempty"` // Default 0.98
	MinStableFrames    int32   `protobuf:"varint,4,opt,name=min_stable_frames,json=minStableFrames,proto3" json:"min_stable_frames,omitempty"`         // Default 3
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DetectStabilityRequest) Reset() {
	*x = DetectStabilityRequest{}
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectStabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectStabilityRequest) ProtoMessage() {}

func (x *DetectStabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectStabilityRequest.ProtoReflect.Descriptor instead.
func (*DetectStabilityRequest) Descriptor() ([]byte, []int) {
	return file_internal_vjepa_proto_vjepa_proto_rawDescGZIP(), []int{5}
}

func (x *DetectStabilityRequest) GetFrames() [][]byte {
	if x != nil {
		return x.Frames
	}
	return nil
}

func (x *DetectStabilityRequest) GetFrameUris() []string {
	if x != nil {
		return x.FrameUris
	}
	return nil
}

func (x *DetectStabilityRequest) GetStabilityThreshold() float32 {
	if x != nil {
		return x.StabilityThreshold
	}
	return 0
}

func (x *DetectStabilityRequest) GetMinStableFrames() int32 {
	if x != nil {
		return x.MinStableFrames
	}
	return 0
}

type DetectStabilityResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IsStable         bool                   `protobuf:"varint,1,opt,name=is_stable,json=isStable,proto3" json:"is_stable,omitempty"`
	StableFrameIndex int32                  `protobuf:"varint,2,opt,name=stable_frame_index,json=stableFrameIndex,proto3" json:"stable_frame_index,omitempty"` // First stable frame
	StabilityScore   float32                `protobuf:"fixed32,3,opt,name=stability_score,json=stabilityScore,proto3" json:"stability_score,omitempty"`
	Analysis         string                 `protobuf:"bytes,4,opt,name=analysis,proto3" json:"analysis,omitempty"` // e.g., "Loading spinner detected"
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DetectStabilityResponse) Reset() {
	*x = DetectStabilityResponse{}
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectStabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectStabilityResponse) ProtoMessage() {}

func (x *DetectStabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectStabilityResponse.ProtoReflect.Descriptor instead.
func (*DetectStabilityResponse) Descriptor() ([]byte, []int) {
	return file_internal_vjepa_proto_vjepa_proto_rawDescGZIP(), []int{6}
}

func (x *DetectStabilityResponse) GetIsStable() bool {
	if x != nil {
		return x.IsStable
	}
	return false
}

func (x *DetectStabilityResponse) GetStableFrameIndex() int32 {
	if x != nil {
		return x.StableFrameIndex
	}
	return 0
}

func (x *DetectStabilityResponse) GetStabilityScore() float32 {
	if x != nil {
		return x.StabilityScore
	}
	return 0
}

func (x *DetectStabilityResponse) GetAnalysis() string {
	if x != nil {
		return x.Analysis
	}
	return ""
}

type GenerateEmbeddingRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ImageData []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	ImageUri  string                 `protobuf:"bytes,2,opt,name=image_uri,json=imageUri,proto3" json:"image_uri,omitempty"`
	// Options
	Normalize     bool `protobuf:"varint,3,opt,name=normalize,proto3" json:"normalize,omitempty"` // L2 normalize embedding
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateEmbeddingRequest) Reset() {
	*x = GenerateEmbeddingRequest{}
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateEmbeddingRequest) ProtoMessage() {}

func (x *GenerateEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*GenerateEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_internal_vjepa_proto_vjepa_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateEmbeddingRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *GenerateEmbeddingRequest) GetImageUri() string {
	if x != nil {
		return x.ImageUri
	}
	return ""
}

func (x *GenerateEmbeddingRequest) GetNormalize() bool {
	if x != nil {
		return x.Normalize
	}
	return false
}

type GenerateEmbeddingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []byte                 `protobuf:"bytes,1,opt,name=embedding,proto3" json:"embedding,omitempty"`                            // Float32 array as bytes
	EmbeddingDim  int32                  `protobuf:"varint,2,opt,name=embedding_dim,json=embeddingDim,proto3" json:"embedding_dim,omitempty"` // Dimension (e.g., 1024)
	ModelVersion  string                 `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`  // For compatibility tracking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateEmbeddingResponse) Reset() {
	*x = GenerateEmbeddingResponse{}
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateEmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateEmbeddingResponse) ProtoMessage() {}

func (x *GenerateEmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateEmbeddingResponse.ProtoReflect.Descriptor instead.
func (*GenerateEmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_internal_vjepa_proto_vjepa_proto_rawDescGZIP(), []int{8}
}

func (x *GenerateEmbeddingResponse) GetEmbedding() []byte {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *GenerateEmbeddingResponse) GetEmbeddingDim() int32 {
	if x != nil {
		return x.EmbeddingDim
	}
	return 0
}

func (x *GenerateEmbeddingResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

type BatchCompareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pairs         []*FramePair           `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	Settings      *CompareSettings       `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCompareRequest) Reset() {
	*x = BatchCompareRequest{}
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCompareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCompareRequest) ProtoMessage() {}

func (x *BatchCompareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCompareRequest.ProtoReflect.Descriptor instead.
func (*BatchCompareRequest) Descriptor() ([]byte, []int) {
	return file_internal_vjepa_proto_vjepa_proto_rawDescGZIP(), []int{9}
}

func (x *BatchCompareRequest) GetPairs() []*FramePair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

func (x *BatchCompareRequest) GetSettings() *CompareSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type FramePair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PairId        string                 `protobuf:"bytes,1,opt,name=pair_id,json=pairId,proto3" json:"pair_id,omitempty"`
	BaselineData  []byte                 `protobuf:"bytes,2,opt,name=baseline_data,json=baselineData,proto3" json:"baseline_data,omitempty"`
	BaselineUri   string                 `protobuf:"bytes,3,opt,name=baseline_uri,json=baselineUri,proto3" json:"baseline_uri,omitempty"`
	ActualData    []byte                 `protobuf:"bytes,4,opt,name=actual_data,json=actualData,proto3" json:"actual_data,omitempty"`
	ActualUri     string                 `protobuf:"bytes,5,opt,name=actual_uri,json=actualUri,proto3" json:"actual_uri,omitempty"`
	Context       string                 `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FramePair) Reset() {
	*x = FramePair{}
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FramePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FramePair) ProtoMessage() {}

func (x *FramePair) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FramePair.ProtoReflect.Descriptor instead.
func (*FramePair) Descriptor() ([]byte, []int) {
	return file_internal_vjepa_proto_vjepa_proto_rawDescGZIP(), []int{10}
}

func (x *FramePair) GetPairId() string {
	if x != nil {
		return x.PairId
	}
	return ""
}

func (x *FramePair) GetBaselineData() []byte {
	if x != nil {
		return x.BaselineData
	}
	return nil
}

func (x *FramePair) GetBaselineUri() string {
	if x != nil {
		return x.BaselineUri
	}
	return ""
}

func (x *FramePair) GetActualData() []byte {
	if x != nil {
		return x.ActualData
	}
	return nil
}

func (x *FramePair) GetActualUri() string {
	if x != nil {
		return x.ActualUri
	}
	return ""
}

func (x *FramePair) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type BatchCompareResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Results           []*BatchCompareResult  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	AverageSimilarity float32                `protobuf:"fixed32,2,opt,name=average_similarity,json=averageSimilarity,proto3" json:"average_similarity,omitempty"`
	Matches           int32                  `protobuf:"varint,3,opt,name=matches,proto3" json:"matches,omitempty"`
	Mismatches        int32                  `protobuf:"varint,4,opt,name=mismatches,proto3" json:"mismatches,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BatchCompareResponse) Reset() {
	*x = BatchCompareResponse{}
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCompareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCompareResponse) ProtoMessage() {}

func (x *BatchCompareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCompareResponse.ProtoReflect.Descriptor instead.
func (*BatchCompareResponse) Descriptor() ([]byte, []int) {
	return file_internal_vjepa_proto_vjepa_proto_rawDescGZIP(), []int{11}
}

func (x *BatchCompareResponse) GetResults() []*BatchCompareResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *BatchCompareResponse) GetAverageSimilarity() float32 {
	if x != nil {
		return x.AverageSimilarity
	}
	return 0
}

func (x *BatchCompareResponse) GetMatches() int32 {
	if x != nil {
		return x.Matches
	}
	return 0
}

func (x *BatchCompareResponse) GetMismatches() int32 {
	if x != nil {
		return x.Mismatches
	}
	return 0
}

type BatchCompareResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PairId        string                 `protobuf:"bytes,1,opt,name=pair_id,json=pairId,proto3" json:"pair_id,omitempty"`
	Result        *CompareFramesResponse `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCompareResult) Reset() {
	*x = BatchCompareResult{}
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCompareResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCompareResult) ProtoMessage() {}

func (x *BatchCompareResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCompareResult.ProtoReflect.Descriptor instead.
func (*BatchCompareResult) Descriptor() ([]byte, []int) {
	return file_internal_vjepa_proto_vjepa_proto_rawDescGZIP(), []int{12}
}

func (x *BatchCompareResult) GetPairId() string {
	if x != nil {
		return x.PairId
	}
	return ""
}

func (x *BatchCompareResult) GetResult() *CompareFramesResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

type AnalyzeChangeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BeforeData      []byte                 `protobuf:"bytes,1,opt,name=before_data,json=beforeData,proto3" json:"before_data,omitempty"`
	BeforeUri       string                 `protobuf:"bytes,2,opt,name=before_uri,json=beforeUri,proto3" json:"before_uri,omitempty"`
	AfterData       []byte                 `protobuf:"bytes,3,opt,name=after_data,json=afterData,proto3" json:"after_data,omitempty"`
	AfterUri        string                 `protobuf:"bytes,4,opt,name=after_uri,json=afterUri,proto3" json:"after_uri,omitempty"`
	ActionPerformed string                 `protobuf:"bytes,5,opt,name=action_performed,json=actionPerformed,proto3" json:"action_performed,omitempty"` // e.g., "clicked submit button"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalyzeChangeRequest) Reset() {
	*x = AnalyzeChangeRequest{}
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeChangeRequest) ProtoMessage() {}

func (x *AnalyzeChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeChangeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeChangeRequest) Descriptor() ([]byte, []int) {
	return file_internal_vjepa_proto_vjepa_proto_rawDescGZIP(), []int{13}
}

func (x *AnalyzeChangeRequest) GetBeforeData() []byte {
	if x != nil {
		return x.BeforeData
	}
	return nil
}

func (x *AnalyzeChangeRequest) GetBeforeUri() string {
	if x != nil {
		return x.BeforeUri
	}
	return ""
}

func (x *AnalyzeChangeRequest) GetAfterData() []byte {
	if x != nil {
		return x.AfterData
	}
	return nil
}

func (x *AnalyzeChangeRequest) GetAfterUri() string {
	if x != nil {
		return x.AfterUri
	}
	return ""
}

func (x *AnalyzeChangeRequest) GetActionPerformed() string {
	if x != nil {
		return x.ActionPerformed
	}
	return ""
}

type AnalyzeChangeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Description    string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`                              // Human-readable change description
	Changes        []string               `protobuf:"bytes,2,rep,name=changes,proto3" json:"changes,omitempty"`                                      // List of detected changes
	ExpectedChange bool                   `protobuf:"varint,3,opt,name=expected_change,json=expectedChange,proto3" json:"expected_change,omitempty"` // Does change match expected behavior?
	Confidence     float32                `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzeChangeResponse) Reset() {
	*x = AnalyzeChangeResponse{}
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeChangeResponse) ProtoMessage() {}

func (x *AnalyzeChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeChangeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeChangeResponse) Descriptor() ([]byte, []int) {
	return file_internal_vjepa_proto_vjepa_proto_rawDescGZIP(), []int{14}
}

func (x *AnalyzeChangeResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AnalyzeChangeResponse) GetChanges() []string {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *AnalyzeChangeResponse) GetExpectedChange() bool {
	if x != nil {
		return x.ExpectedChange
	}
	return false
}

func (x *AnalyzeChangeResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_internal_vjepa_proto_vjepa_proto_rawDescGZIP(), []int{15}
}

type HealthCheckResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Healthy        bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ModelLoaded    string                 `protobuf:"bytes,2,opt,name=model_loaded,json=modelLoaded,proto3" json:"model_loaded,omitempty"`
	Device         string                 `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"` // cuda:0, cpu
	MemoryUsedMb   int64                  `protobuf:"varint,4,opt,name=memory_used_mb,json=memoryUsedMb,proto3" json:"memory_used_mb,omitempty"`
	MemoryTotalMb  int64                  `protobuf:"varint,5,opt,name=memory_total_mb,json=memoryTotalMb,proto3" json:"memory_total_mb,omitempty"`
	AvgInferenceMs float32                `protobuf:"fixed32,6,opt,name=avg_inference_ms,json=avgInferenceMs,proto3" json:"avg_inference_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_vjepa_proto_vjepa_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_internal_vjepa_proto_vjepa_proto_rawDescGZIP(), []int{16}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetModelLoaded() string {
	if x != nil {
		return x.ModelLoaded
	}
	return ""
}

func (x *HealthCheckResponse) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *HealthCheckResponse) GetMemoryUsedMb() int64 {
	if x != nil {
		return x.MemoryUsedMb
	}
	return 0
}

func (x *HealthCheckResponse) GetMemoryTotalMb() int64 {
	if x != nil {
		return x.MemoryTotalMb
	}
	return 0
}

func (x *HealthCheckResponse) GetAvgInferenceMs() float32 {
	if x != nil {
		return x.AvgInferenceMs
	}
	return 0
}

var File_internal_vjepa_proto_vjepa_proto protoreflect.FileDescriptor

const file_internal_vjepa_proto_vjepa_proto_rawDesc = "" +
	"\n" +
	" internal/vjepa/proto/vjepa.proto\x12\x05vjepa\"\xec\x01\n" +
	"\x14CompareFramesRequest\x12#\n" +
	"\rbaseline_data\x18\x01 \x01(\fR\fbaselineData\x12!\n" +
	"\fbaseline_uri\x18\x02 \x01(\tR\vbaselineUri\x12\x1f\n" +
	"\vactual_data\x18\x03 \x01(\fR\n" +
	"actualData\x12\x1d\n" +
	"\n" +
	"actual_uri\x18\x04 \x01(\tR\tactualUri\x12\x18\n" +
	"\acontext\x18\x05 \x01(\tR\acontext\x122\n" +
	"\bsettings\x18\x06 \x01(\v2\x16.vjepa.CompareSettingsR\bsettings\"\xcf\x01\n" +
	"\x0fCompareSettings\x121\n" +
	"\x14similarity_threshold\x18\x01 \x01(\x02R\x13similarityThreshold\x12#\n" +
	"\rignore_colors\x18\x02 \x01(\bR\fignoreColors\x12.\n" +
	"\x13ignore_text_content\x18\x03 \x01(\bR\x11ignoreTextContent\x124\n" +
	"\x0eignore_regions\x18\x04 \x03(\v2\r.vjepa.RegionR\rignoreRegions\"R\n" +
	"\x06Region\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\"\xbe\x02\n" +
	"\x15CompareFramesResponse\x12)\n" +
	"\x10similarity_score\x18\x01 \x01(\x02R\x0fsimilarityScore\x12%\n" +
	"\x0esemantic_match\x18\x02 \x01(\bR\rsemanticMatch\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12=\n" +
	"\x0fchanged_regions\x18\x04 \x03(\v2\x14.vjepa.ChangedRegionR\x0echangedRegions\x12\x1a\n" +
	"\banalysis\x18\x05 \x01(\tR\banalysis\x12-\n" +
	"\x12baseline_embedding\x18\x06 \x01(\fR\x11baselineEmbedding\x12)\n" +
	"\x10actual_embedding\x18\a \x01(\fR\x0factualEmbedding\"\x9d\x01\n" +
	"\rChangedRegion\x12%\n" +
	"\x06region\x18\x01 \x01(\v2\r.vjepa.RegionR\x06region\x12\x1f\n" +
	"\vchange_type\x18\x02 \x01(\tR\n" +
	"changeType\x12\"\n" +
	"\fsignificance\x18\x03 \x01(\x02R\fsignificance\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xac\x01\n" +
	"\x16DetectStabilityRequest\x12\x16\n" +
	"\x06frames\x18\x01 \x03(\fR\x06frames\x12\x1d\n" +
	"\n" +
	"frame_uris\x18\x02 \x03(\tR\tframeUris\x12/\n" +
	"\x13stability_threshold\x18\x03 \x01(\x02R\x12stabilityThreshold\x12*\n" +
	"\x11min_stable_frames\x18\x04 \x01(\x05R\x0fminStableFrames\"\xa9\x01\n" +
	"\x17DetectStabilityResponse\x12\x1b\n" +
	"\tis_stable\x18\x01 \x01(\bR\bisStable\x12,\n" +
	"\x12stable_frame_index\x18\x02 \x01(\x05R\x10stableFrameIndex\x12'\n" +
	"\x0fstability_score\x18\x03 \x01(\x02R\x0estabilityScore\x12\x1a\n" +
	"\banalysis\x18\x04 \x01(\tR\banalysis\"t\n" +
	"\x18GenerateEmbeddingRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12\x1b\n" +
	"\timage_uri\x18\x02 \x01(\tR\bimageUri\x12\x1c\n" +
	"\tnormalize\x18\x03 \x01(\bR\tnormalize\"\x83\x01\n" +
	"\x19GenerateEmbeddingResponse\x12\x1c\n" +
	"\tembedding\x18\x01 \x01(\fR\tembedding\x12#\n" +
	"\rembedding_dim\x18\x02 \x01(\x05R\fembeddingDim\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion\"q\n" +
	"\x13BatchCompareRequest\x12&\n" +
	"\x05pairs\x18\x01 \x03(\v2\x10.vjepa.FramePairR\x05pairs\x122\n" +
	"\bsettings\x18\x02 \x01(\v2\x16.vjepa.CompareSettingsR\bsettings\"\xc6\x01\n" +
	"\tFramePair\x12\x17\n" +
	"\apair_id\x18\x01 \x01(\tR\x06pairId\x12#\n" +
	"\rbaseline_data\x18\x02 \x01(\fR\fbaselineData\x12!\n" +
	"\fbaseline_uri\x18\x03 \x01(\tR\vbaselineUri\x12\x1f\n" +
	"\vactual_data\x18\x04 \x01(\fR\n" +
	"actualData\x12\x1d\n" +
	"\n" +
	"actual_uri\x18\x05 \x01(\tR\tactualUri\x12\x18\n" +
	"\acontext\x18\x06 \x01(\tR\acontext\"\xb4\x01\n" +
	"\x14BatchCompareResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.vjepa.BatchCompareResultR\aresults\x12-\n" +
	"\x12average_similarity\x18\x02 \x01(\x02R\x11averageSimilarity\x12\x18\n" +
	"\amatches\x18\x03 \x01(\x05R\amatches\x12\x1e\n" +
	"\n" +
	"mismatches\x18\x04 \x01(\x05R\n" +
	"mismatches\"c\n" +
	"\x12BatchCompareResult\x12\x17\n" +
	"\apair_id\x18\x01 \x01(\tR\x06pairId\x124\n" +
	"\x06result\x18\x02 \x01(\v2\x1c.vjepa.CompareFramesResponseR\x06result\"\xbd\x01\n" +
	"\x14AnalyzeChangeRequest\x12\x1f\n" +
	"\vbefore_data\x18\x01 \x01(\fR\n" +
	"beforeData\x12\x1d\n" +
	"\n" +
	"before_uri\x18\x02 \x01(\tR\tbeforeUri\x12\x1d\n" +
	"\n" +
	"after_data\x18\x03 \x01(\fR\tafterData\x12\x1b\n" +
	"\tafter_uri\x18\x04 \x01(\tR\bafterUri\x12)\n" +
	"\x10action_performed\x18\x05 \x01(\tR\x0factionPerformed\"\x9c\x01\n" +
	"\x15AnalyzeChangeResponse\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x18\n" +
	"\achanges\x18\x02 \x03(\tR\achanges\x12'\n" +
	"\x0fexpected_change\x18\x03 \x01(\bR\x0eexpectedChange\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\"\x14\n" +
	"\x12HealthCheckRequest\"\xe2\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12!\n" +
	"\fmodel_loaded\x18\x02 \x01(\tR\vmodelLoaded\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\x12$\n" +
	"\x0ememory_used_mb\x18\x04 \x01(\x03R\fmemoryUsedMb\x12&\n" +
	"\x0fmemory_total_mb\x18\x05 \x01(\x03R\rmemoryTotalMb\x12(\n" +
	"\x10avg_inference_ms\x18\x06 \x01(\x02R\x0eavgInferenceMs2\xdf\x03\n" +
	"\fVJEPAService\x12J\n" +
	"\rCompareFrames\x12\x1b.vjepa.CompareFramesRequest\x1a\x1c.vjepa.CompareFramesResponse\x12P\n" +
	"\x0fDetectStability\x12\x1d.vjepa.DetectStabilityRequest\x1a\x1e.vjepa.DetectStabilityResponse\x12V\n" +
	"\x11GenerateEmbedding\x12\x1f.vjepa.GenerateEmbeddingRequest\x1a .vjepa.GenerateEmbeddingResponse\x12G\n" +
	"\fBatchCompare\x12\x1a.vjepa.BatchCompareRequest\x1a\x1b.vjepa.BatchCompareResponse\x12J\n" +
	"\rAnalyzeChange\x12\x1b.vjepa.AnalyzeChangeRequest\x1a\x1c.vjepa.AnalyzeChangeResponse\x12D\n" +
	"\vHealthCheck\x12\x19.vjepa.HealthCheckRequest\x1a\x1a.vjepa.HealthCheckResponseB5Z3github.com/testforge/testforge/internal/vjepa/protob\x06proto3"

var (
	file_internal_vjepa_proto_vjepa_proto_rawDescOnce sync.Once
	file_internal_vjepa_proto_vjepa_proto_rawDescData []byte
)

func file_internal_vjepa_proto_vjepa_proto_rawDescGZIP() []byte {
	file_internal_vjepa_proto_vjepa_proto_rawDescOnce.Do(func() {
		file_internal_vjepa_proto_vjepa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_vjepa_proto_vjepa_proto_rawDesc), len(file_internal_vjepa_proto_vjepa_proto_rawDesc)))
	})
	return file_internal_vjepa_proto_vjepa_proto_rawDescData
}

var file_internal_vjepa_proto_vjepa_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_internal_vjepa_proto_vjepa_proto_goTypes = []any{
	(*CompareFramesRequest)(nil),      // 0: vjepa.CompareFramesRequest
	(*CompareSettings)(nil),           // 1: vjepa.CompareSettings
	(*Region)(nil),                    // 2: vjepa.Region
	(*CompareFramesResponse)(nil),     // 3: vjepa.CompareFramesResponse
	(*ChangedRegion)(nil),             // 4: vjepa.ChangedRegion
	(*DetectStabilityRequest)(nil),    // 5: vjepa.DetectStabilityRequest
	(*DetectStabilityResponse)(nil),   // 6: vjepa.DetectStabilityResponse
	(*GenerateEmbeddingRequest)(nil),  // 7: vjepa.GenerateEmbeddingRequest
	(*GenerateEmbeddingResponse)(nil), // 8: vjepa.GenerateEmbeddingResponse
	(*BatchCompareRequest)(nil),       // 9: vjepa.BatchCompareRequest
	(*FramePair)(nil),                 // 10: vjepa.FramePair
	(*BatchCompareResponse)(nil),      // 11: vjepa.BatchCompareResponse
	(*BatchCompareResult)(nil),        // 12: vjepa.BatchCompareResult
	(*AnalyzeChangeRequest)(nil),      // 13: vjepa.AnalyzeChangeRequest
	(*AnalyzeChangeResponse)(nil),     // 14: vjepa.AnalyzeChangeResponse
	(*HealthCheckRequest)(nil),        // 15: vjepa.HealthCheckRequest
	(*HealthCheckResponse)(nil),       // 16: vjepa.HealthCheckResponse
}
var file_internal_vjepa_proto_vjepa_proto_depIdxs = []int32{
	1,  // 0: vjepa.CompareFramesRequest.settings:type_name -> vjepa.CompareSettings
	2,  // 1: vjepa.CompareSettings.ignore_regions:type_name -> vjepa.Region
	4,  // 2: vjepa.CompareFramesResponse.changed_regions:type_name -> vjepa.ChangedRegion
	2,  // 3: vjepa.ChangedRegion.region:type_name -> vjepa.Region
	10, // 4: vjepa.BatchCompareRequest.pairs:type_name -> vjepa.FramePair
	1,  // 5: vjepa.BatchCompareRequest.settings:type_name -> vjepa.CompareSettings
	12, // 6: vjepa.BatchCompareResponse.results:type_name -> vjepa.BatchCompareResult
	3,  // 7: vjepa.BatchCompareResult.result:type_name -> vjepa.CompareFramesResponse
	0,  // 8: vjepa.VJEPAService.CompareFrames:input_type -> vjepa.CompareFramesRequest
	5,  // 9: vjepa.VJEPAService.DetectStability:input_type -> vjepa.DetectStabilityRequest
	7,  // 10: vjepa.VJEPAService.GenerateEmbedding:input_type -> vjepa.GenerateEmbeddingRequest
	9,  // 11: vjepa.VJEPAService.BatchCompare:input_type -> vjepa.BatchCompareRequest
	13, // 12: vjepa.VJEPAService.AnalyzeChange:input_type -> vjepa.AnalyzeChangeRequest
	15, // 13: vjepa.VJEPAService.HealthCheck:input_type -> vjepa.HealthCheckRequest
	3,  // 14: vjepa.VJEPAService.CompareFrames:output_type -> vjepa.CompareFramesResponse
	6,  // 15: vjepa.VJEPAService.DetectStability:output_type -> vjepa.DetectStabilityResponse
	8,  // 16: vjepa.VJEPAService.GenerateEmbedding:output_type -> vjepa.GenerateEmbeddingResponse
	11, // 17: vjepa.VJEPAService.BatchCompare:output_type -> vjepa.BatchCompareResponse
	14, // 18: vjepa.VJEPAService.AnalyzeChange:output_type -> vjepa.AnalyzeChangeResponse
	16, // 19: vjepa.VJEPAService.HealthCheck:output_type -> vjepa.HealthCheckResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_internal_vjepa_proto_vjepa_proto_init() }
func file_internal_vjepa_proto_vjepa_proto_init() {
	if File_internal_vjepa_proto_vjepa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_vjepa_proto_vjepa_proto_rawDesc), len(file_internal_vjepa_proto_vjepa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_vjepa_proto_vjepa_proto_goTypes,
		DependencyIndexes: file_internal_vjepa_proto_vjepa_proto_depIdxs,
		MessageInfos:      file_internal_vjepa_proto_vjepa_proto_msgTypes,
	}.Build()
	File_internal_vjepa_proto_vjepa_proto = out.File
	file_internal_vjepa_proto_vjepa_proto_goTypes = nil
	file_internal_vjepa_proto_vjepa_proto_depIdxs = nil
}
