# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import visual_ai_pb2 as visual__ai__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in visual_ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VisualAIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CompareFrames = channel.unary_unary(
                '/visualai.VisualAIService/CompareFrames',
                request_serializer=visual__ai__pb2.CompareFramesRequest.SerializeToString,
                response_deserializer=visual__ai__pb2.CompareFramesResponse.FromString,
                _registered_method=True)
        self.DetectStability = channel.unary_unary(
                '/visualai.VisualAIService/DetectStability',
                request_serializer=visual__ai__pb2.DetectStabilityRequest.SerializeToString,
                response_deserializer=visual__ai__pb2.DetectStabilityResponse.FromString,
                _registered_method=True)
        self.ValidateHealing = channel.unary_unary(
                '/visualai.VisualAIService/ValidateHealing',
                request_serializer=visual__ai__pb2.ValidateHealingRequest.SerializeToString,
                response_deserializer=visual__ai__pb2.ValidateHealingResponse.FromString,
                _registered_method=True)
        self.GenerateEmbedding = channel.unary_unary(
                '/visualai.VisualAIService/GenerateEmbedding',
                request_serializer=visual__ai__pb2.GenerateEmbeddingRequest.SerializeToString,
                response_deserializer=visual__ai__pb2.GenerateEmbeddingResponse.FromString,
                _registered_method=True)
        self.BatchCompare = channel.unary_unary(
                '/visualai.VisualAIService/BatchCompare',
                request_serializer=visual__ai__pb2.BatchCompareRequest.SerializeToString,
                response_deserializer=visual__ai__pb2.BatchCompareResponse.FromString,
                _registered_method=True)
        self.FindByDescription = channel.unary_unary(
                '/visualai.VisualAIService/FindByDescription',
                request_serializer=visual__ai__pb2.FindByDescriptionRequest.SerializeToString,
                response_deserializer=visual__ai__pb2.FindByDescriptionResponse.FromString,
                _registered_method=True)
        self.AnalyzeChange = channel.unary_unary(
                '/visualai.VisualAIService/AnalyzeChange',
                request_serializer=visual__ai__pb2.AnalyzeChangeRequest.SerializeToString,
                response_deserializer=visual__ai__pb2.AnalyzeChangeResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/visualai.VisualAIService/HealthCheck',
                request_serializer=visual__ai__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=visual__ai__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class VisualAIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CompareFrames(self, request, context):
        """Fast comparison using DINOv2 (default)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectStability(self, request, context):
        """Sequence-aware stability detection using V-JEPA 2
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateHealing(self, request, context):
        """Self-healing validation using V-JEPA 2 (understands state transitions)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateEmbedding(self, request, context):
        """Generate embedding (specify model)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchCompare(self, request, context):
        """Batch comparison
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindByDescription(self, request, context):
        """Find element by description using SigLIP
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeChange(self, request, context):
        """Analyze visual change between frames
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VisualAIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CompareFrames': grpc.unary_unary_rpc_method_handler(
                    servicer.CompareFrames,
                    request_deserializer=visual__ai__pb2.CompareFramesRequest.FromString,
                    response_serializer=visual__ai__pb2.CompareFramesResponse.SerializeToString,
            ),
            'DetectStability': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectStability,
                    request_deserializer=visual__ai__pb2.DetectStabilityRequest.FromString,
                    response_serializer=visual__ai__pb2.DetectStabilityResponse.SerializeToString,
            ),
            'ValidateHealing': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateHealing,
                    request_deserializer=visual__ai__pb2.ValidateHealingRequest.FromString,
                    response_serializer=visual__ai__pb2.ValidateHealingResponse.SerializeToString,
            ),
            'GenerateEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateEmbedding,
                    request_deserializer=visual__ai__pb2.GenerateEmbeddingRequest.FromString,
                    response_serializer=visual__ai__pb2.GenerateEmbeddingResponse.SerializeToString,
            ),
            'BatchCompare': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchCompare,
                    request_deserializer=visual__ai__pb2.BatchCompareRequest.FromString,
                    response_serializer=visual__ai__pb2.BatchCompareResponse.SerializeToString,
            ),
            'FindByDescription': grpc.unary_unary_rpc_method_handler(
                    servicer.FindByDescription,
                    request_deserializer=visual__ai__pb2.FindByDescriptionRequest.FromString,
                    response_serializer=visual__ai__pb2.FindByDescriptionResponse.SerializeToString,
            ),
            'AnalyzeChange': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeChange,
                    request_deserializer=visual__ai__pb2.AnalyzeChangeRequest.FromString,
                    response_serializer=visual__ai__pb2.AnalyzeChangeResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=visual__ai__pb2.HealthCheckRequest.FromString,
                    response_serializer=visual__ai__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'visualai.VisualAIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('visualai.VisualAIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VisualAIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CompareFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visualai.VisualAIService/CompareFrames',
            visual__ai__pb2.CompareFramesRequest.SerializeToString,
            visual__ai__pb2.CompareFramesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectStability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visualai.VisualAIService/DetectStability',
            visual__ai__pb2.DetectStabilityRequest.SerializeToString,
            visual__ai__pb2.DetectStabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateHealing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visualai.VisualAIService/ValidateHealing',
            visual__ai__pb2.ValidateHealingRequest.SerializeToString,
            visual__ai__pb2.ValidateHealingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visualai.VisualAIService/GenerateEmbedding',
            visual__ai__pb2.GenerateEmbeddingRequest.SerializeToString,
            visual__ai__pb2.GenerateEmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchCompare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visualai.VisualAIService/BatchCompare',
            visual__ai__pb2.BatchCompareRequest.SerializeToString,
            visual__ai__pb2.BatchCompareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindByDescription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visualai.VisualAIService/FindByDescription',
            visual__ai__pb2.FindByDescriptionRequest.SerializeToString,
            visual__ai__pb2.FindByDescriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visualai.VisualAIService/AnalyzeChange',
            visual__ai__pb2.AnalyzeChangeRequest.SerializeToString,
            visual__ai__pb2.AnalyzeChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/visualai.VisualAIService/HealthCheck',
            visual__ai__pb2.HealthCheckRequest.SerializeToString,
            visual__ai__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
