# Temporal Server Deployment for TestForge
# Provides workflow orchestration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-config
  namespace: testforge-temporal
data:
  dynamicconfig.yaml: |
    # Temporal dynamic configuration
    system.forceSearchAttributesCacheRefreshOnRead:
      - value: true
    limit.maxIDLength:
      - value: 255
    history.defaultActivityRetryPolicy.InitialIntervalInSeconds:
      - value: 1
    history.defaultActivityRetryPolicy.MaximumIntervalInSeconds:
      - value: 100
    history.defaultActivityRetryPolicy.BackoffCoefficient:
      - value: 2.0
    history.defaultActivityRetryPolicy.MaximumAttempts:
      - value: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  namespace: testforge-temporal
  labels:
    app: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z postgres.testforge-data.svc.cluster.local 5432; do
                echo "Waiting for PostgreSQL..."
                sleep 2
              done
              echo "PostgreSQL is ready"
      containers:
        - name: temporal
          image: temporalio/auto-setup:latest
          ports:
            - containerPort: 7233
              name: grpc
          env:
            - name: DB
              value: postgresql
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
                  optional: false
            - name: POSTGRES_PWD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
                  optional: false
            - name: POSTGRES_SEEDS
              value: postgres.testforge-data.svc.cluster.local
            - name: DYNAMIC_CONFIG_FILE_PATH
              value: /etc/temporal/dynamicconfig.yaml
            - name: SKIP_DEFAULT_NAMESPACE_CREATION
              value: "false"
            - name: DEFAULT_NAMESPACE
              value: testforge
            - name: TEMPORAL_CLI_ADDRESS
              value: temporal.testforge-temporal.svc.cluster.local:7233
          volumeMounts:
            - name: config
              mountPath: /etc/temporal
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            exec:
              command:
                - tctl
                - --address
                - localhost:7233
                - cluster
                - health
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
                - tctl
                - --address
                - localhost:7233
                - cluster
                - health
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: config
          configMap:
            name: temporal-config
---
apiVersion: v1
kind: Service
metadata:
  name: temporal
  namespace: testforge-temporal
spec:
  selector:
    app: temporal
  ports:
    - port: 7233
      targetPort: 7233
      name: grpc
  type: ClusterIP
---
# Temporal Web UI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-ui
  namespace: testforge-temporal
  labels:
    app: temporal-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-ui
  template:
    metadata:
      labels:
        app: temporal-ui
    spec:
      containers:
        - name: temporal-ui
          image: temporalio/ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: TEMPORAL_ADDRESS
              value: temporal.testforge-temporal.svc.cluster.local:7233
            - name: TEMPORAL_CORS_ORIGINS
              value: http://localhost:3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-ui
  namespace: testforge-temporal
spec:
  selector:
    app: temporal-ui
  ports:
    - port: 8088
      targetPort: 8080
  type: ClusterIP
---
# Secret reference for Temporal to access Postgres
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: testforge-temporal
type: Opaque
stringData:
  POSTGRES_USER: testforge
  POSTGRES_PASSWORD: testforge-secret-password
