# TestForge Database Migrations Job
# Run this before deploying API and Worker
---
apiVersion: batch/v1
kind: Job
metadata:
  name: testforge-migrations
  namespace: testforge
  labels:
    app: testforge-migrations
spec:
  ttlSecondsAfterFinished: 300  # Clean up after 5 minutes
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: testforge-migrations
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: ghcr-secret
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z postgres.testforge-data.svc.cluster.local 5432; do
                echo "Waiting for PostgreSQL..."
                sleep 2
              done
              echo "PostgreSQL is ready"
      containers:
        - name: migrate
          image: ghcr.io/testforge-hq/testforge/migrate:v0.1.0
          env:
            - name: DB_HOST
              value: postgres.testforge-data.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: testforge-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: testforge-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: testforge-secrets
                  key: DB_NAME
