# Sandbox Namespace Configuration
# Isolated environment for test execution
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: sandbox-quota
  namespace: testforge-sandbox
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "50"
    persistentvolumeclaims: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: sandbox-limits
  namespace: testforge-sandbox
spec:
  limits:
    - default:
        cpu: "1"
        memory: "2Gi"
      defaultRequest:
        cpu: "250m"
        memory: "512Mi"
      max:
        cpu: "2"
        memory: "4Gi"
      min:
        cpu: "100m"
        memory: "128Mi"
      type: Container
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sandbox-isolation
  namespace: testforge-sandbox
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow from testforge namespace (worker)
    - from:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/name: testforge
  egress:
    # Allow DNS
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
    # Allow HTTPS outbound (for testing web apps)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
    # Allow to MinIO for artifact storage
    - to:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/component: data
      ports:
        - protocol: TCP
          port: 9000
